### ISSUE TITLE
请问微调后模型的路径 指的是什么

### ISSUE THREAD

**Issue by bixingjian** [zhoujx4/DuIE#1]
这个微调后模型的路径指的是什么呢 是best_model.pkl吗

**Comment by zhoujx4** [comment]
没错，就是best_model.pkl的路径




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhoujx4/DuIE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 上午8:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhoujx4/DuIE] 请问微调后模型的路径 指的是什么 (#1)





 
这个微调后模型的路径指的是什么呢 是best_model.pkl吗
